DELETE http://localhost:3001/api/persons/68d39fe244409c9ba8a5e766

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/

###

PUT http://localhost:3001/api/persons/68d39f8dfeda68217f6d9b21
Content-Type: application/json

{
  "name": "Aku Ankka",
  "number": "040-11111111"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Aku Ankka",
  "number": "040-1234567"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Aku Ankka"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "number": "040-1234567"
}